### ISSUE TITLE
Definir estratégia para inserção dos dados de 2017

### ISSUE THREAD

**Issue by paulofelipefeitosa** [OpenEnade/API#17]
Os dados de 2017 estão disponíveis nesse [link](http://portal.inep.gov.br/conceito-enade) e serão usados como referência para a aplicação.

**Comment by Icaro-Lima** [comment]
Deixa comigo, farei agora.

**Comment by paulofelipefeitosa** [comment]
@Icaro-Lima thanks :smile:

**Comment by Icaro-Lima** [comment]
Pensei no seguinte, a gente faz upload do arquivo `.xls` por meio do PostMapping, em seguida a gente pega esse arquivo e envia pro service, esse service precisa saber ler cada linha do arquivo `.xls` e ir inserindo nos outros services.

**Comment by paulofelipefeitosa** [comment]
@Icaro-Lima are you suggesting that the code for the data insertion be placed inside the API code?

**Comment by Icaro-Lima** [comment]
@paulofelipefeitosa Yes. For security, you need an access token.

**Comment by Icaro-Lima** [comment]
Ok, great.

**Comment by paulofelipefeitosa** [comment]
@Icaro-Lima but we can discuss your idea, maybe we should have a video call :smile: .
